### ISSUE TITLE
Hardcoded paths in produce.cc

### ISSUE THREAD

**Issue by jbsauvan** [bfonta/bye_splits#32]
Hardcoded input directory in `produce.cc`
https://github.com/bfonta/bye_splits/blob/ff9e6ec554c89ef70038cc4d48460d960bf3f76e/bye_splits/production/produce.cc#L78
While we should expect it to be read from the configuration file
https://github.com/bfonta/bye_splits/blob/ff9e6ec554c89ef70038cc4d48460d960bf3f76e/bye_splits/production/prod_params.yaml#L4-L6

In addition,  at the moment it can only use the same base directory for input and output files:
https://github.com/bfonta/bye_splits/blob/ff9e6ec554c89ef70038cc4d48460d960bf3f76e/bye_splits/production/produce.cc#L92

But the input directory could be read-only (for instance if reading data in another user directory), so it would be better to have a separate base directory to store the output. And ideally this output base directory should be configurable as well.

**Comment by isehle** [comment]
I've rewritten [```produce.cc```](https://github.com/isehle/bye_splits/blob/9370c3a051e8fe76ca9334b5c73a3d2fa116d6fb/bye_splits/production/produce.cc#L144) so that it can be run without any arguments, using the input information in ```prod_params.yaml```. It now accepts an optional ```--inpath``` argument if you wish to run it on a different input file from the one set in the YAML file (very useful for job submission), and the ```--particles``` argument was removed in favor of inferring it from the input file path (which requires the particle name to be somewhere in the path). The ```prod_params.yaml``` file will be deprecated by #26 so I won't open the PR yet, but this should resolve the issue.
